# (1..3).each do |i|
#   config.vm.define "node-#{i}" do |node|
#     node.vm.provision "shell",
#       inline: "echo hello from node #{i}"
#   end
# end
Vagrant.configure("2") do |config|

  vm_name=['web01','mysql01','ftp01']

  vm_name.each do |i|
      config.vm.define "#{i}" do |node|
      node.vm.box = "centos/8"
    end
  end
end
