# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

    config.vm.provider "virtualbox" do |vb|
      vb.name = "artifactory-01"
      vb.memory = 2048
      vb.cpus = 2
    end

    config.vm.box = "centos/8"
    config.vm.hostname = "artifactory-01"
    config.vm.network "private_network", ip: "192.168.33.11"
    config.vm.provision "shell", path: "install_jfrog_centos8.sh"
end
