# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

    config.vm.provider "virtualbox" do |vb|
      vb.name = "jenkins-server-01"
      vb.memory = 1024
      vb.cpus = 2
    end

    config.vm.box = "centos/8"
    config.vm.hostname = "jenkins01"
    config.vm.network "private_network", ip: "192.168.33.10"
    
    config.vm.provision "shell", path: "https://gist.githubusercontent.com/sharadchhetri/cfe3c76791b41b0f245f43dd127b0810/raw/947d9d95159866af0cc1c9fa8d0249c66546a6a8/install-jenkins-centos.sh"

end
